# conda environment description file for FVCOM-Cmd package
# development environment
#
# Create a conda environment in which the `fvcom` command can be run
# with:
#
#   $ conda env create -f FVCOM-Cmd/environment.yaml
#   $ source activate salishsea-cmd
#   (nemo-cmd)$ pip install --editable FVCOM-Cmd
#
# The environment will also include all of the tools used to develop,
# test, and document the FVCOM-Cmd package.
#
# See the requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: fvcom-cmd

channels:
  - defaults
  - gomss-nowcast

dependencies:
  - arrow
  - attrs
  - pip
  - python=3
  - pyyaml

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - cliff
    - python-hglib

    # For code style maintenance
    - yapf
