# conda environment description file for readthedocs build environment

name: gomss-nowcast-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python=3.11

  # readthedocs packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - recommonmark
    - readthedocs-sphinx-ext

    # Install FVCOM-Cmd package in editable mode
    - --editable ../
