# conda environment description file for FVCOM-Cmd package
# development environment
#
# Create a conda environment in which the `fvcom` command can be run
# with:
#
#   $ conda env create -f FVCOM-Cmd/environment.yaml
#   $ conda activate fvcom-cmd
#
# The environment will also include all the tools used to develop,
# test, and document the FVCOM-Cmd package.
#
# See the requirements.txt file for an exhaustive list of all the
# packages installed in the environment and their versions used in
# recent development.

name: fvcom-cmd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - pip
  - python=3.11
  - pyyaml

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - cliff
    - python-hglib

    # For code style maintenance
    - yapf

    # Install the NEMO-Cmd and FVCOM-Cmd packages in editable mode
    - --editable ../NEMO-Cmd
    - --editable ./
