# conda environment description file for readthedocs build environment

name: gomss-nowcast

channels:
  - defaults
  - gomss-nowcast

dependencies:
  - arrow
  - attrs
  - pip
  - python=3
  - pyyaml
  - pip:
    - cliff
    - python-hglib
